spring:
  data:
    mongodb:
      uri: ${URI:mongodb://localhost:27017}
      database: ${DATABASE:execution-service}
  cloud:
    stream:
      bindings:
        output:
          destination:
             add: ${TOPIC_ON_ADD:device-pipeline-add}
             drop: ${TOPIC_ON_DROP:device-pipeline-drop}
    gcp:
      project-id: ${PROJECT_ID:single-system}
server:
  port: ${PORT:9098}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9099}

mongock:
  change-logs-scan-package:
    - com.ynero.ss.execution.migration

