deployment:
  grpc:
    port: 9099
  name: execution-service
  containers:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 6Gi
  replicaCount: 1
  port: 9098
  mongo:
    username: root
    host: my-release-mongodb.default.svc.cluster.local
    port: 27017
    password: ${sm://mongo-admin-password}
    database: execution-service
  redis:
    host: 10.133.169.11
    port: 6379
    timeout: 6000
    expiration: 3000
  projectId: single-system-dev
  kafka:
    bootstrap:
        server: 10.8.15.224:9092
    topic:
      resultsSendingData: results-sending-data
  topic:
    pipeline:
      add: pipeline-adding
      drop: pipeline-deleting
service:
  target:
    port: 9098
actuator:
  server:
    port: 8058
  endpoints:
    web:
      exposure:
        include: '*'
env:
  JDK_JAVA_OPTIONS: "-Xmx3584M"